Add CS:GO
LAN-Party-Gdansk/regulamin pull request #7
Opened 2019-11-04 18:25 UTC by Crokus

Merge it asap!

2019-11-05 12:12 UTC, wojciechT commented
to nie jest ta lista. CS:GO jest poprawnie zgłoszony, ale nie możemy go jeszcze dopisać do listy tytułów „tradycyjnych”

2019-11-05 12:13 UTC, AleksanderXXX approved these changes
CS:GO approve

2019-11-05 13:19 UTC, Crokus commented
CS:GO nie jest tradycyjny, gdyż jest szykanowany od samego poczatku. Różnymi kruczkami prawnymi, niezgodnością z regulaminem.

2019-11-05 13:19 UTC, Crokus commented
Żaden inny tytuł, nie był tak zwalczany, są pewne osoby w pewnych grupach, którym CS:GO jest bardzo nie w smak.

2019-11-05 13:33 UTC, slawomir-kasprowicz commented
CS:GO nie jest grą "tradycyjną" należy go zgłosić poprzez normalną procedurę zgłaszania gier.
czy. regulamin!
![](https://media3.giphy.com/media/VqPpOjb1rOBBS/giphy.gif)

2019-11-05 13:34 UTC, slawomir-kasprowicz requested changes
nope

2019-11-05 13:34 UTC, wojciechT commented
Wypraszam sobie osobiście sugerowanie, że walczymy z CS:GO. Niektórzy z komentujących tutaj mają rangi tak wysokie, jak srebro trzy (jedna z najwyższych rang, dla niezaznajomionych z tematem)!

2019-11-05 13:46 UTC, Crokus commented
Nie chcę się bawić w tanie psychoanalizy, ale to właśnie wysokie zaangażowanie w CS:GO w przeszłości mogło powodować podświadome zwalczanie tej gry czego emanacją były gierki regulaminowe. Wspomniane przez @wojciechT wysokie rangi zdają się potwierdząc tę hipotezę.

2019-11-05 13:47 UTC, wojciechT commented
Faktycznie w tanie psychoanalizy lepiej się nie bawić.

2019-11-05 14:12 UTC, Crokus commented
Jestem rozczarowany, myślałem, że pociągniemy tę dyskusję do co najmniej 20. komentarzy ;)

2019-11-05 14:19 UTC, wojciechT commented
Lepiej poświęcić ten czas na lekturę regulaminu

2019-11-05 14:22 UTC, Crokus commented
Regulamin do tej pory nie był wersjonowany, więc jakiekolwiek powoływanie się na niego w przeszłości skomentować mogę jedynie uśmiechem.

2019-11-05 14:46 UTC, wojciechT commented
Regulamin już przed poprzednią edycją był dostępny jako publiczne repo, został przeniesiony bez istotnych zmian do tego.

2019-11-05 18:41 UTC, AleksanderXXX commented
Dałem approva bo @Crokus oraz @slawomir-kasprowicz  mnie naciskali. Przed dalszymi koniecznymi zmianami chciałbym usłyszeć opinię fachowca, mojego serdecznego przyjaciela, starszego specjalistę od pisania regulaminów @PawelTroka

2019-11-05 21:50 UTC, PawelTroka commented
proponuje dodac bulk-iem wszystkie pozycje zglosze na liste przed eventem jednak zaznaczyc, ze nie sa one pozycjami tradycyjnymi 👍

2019-11-07 08:47 UTC, Crokus commented
Proponuję dodać CS:GO jako pozycję tradycyjnie szykanowaną ;)

2019-11-15 12:18 UTC, closed without merging